/*
 * Service
 *
 * API service
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package main

import (
	"log"
	"net/http"

	"github.com/containerly/golang-service/pkg/example"
)

func main() {
	log.Printf("Server started")

	ResourceAPIService := example.NewResourceAPIService()
	ResourceAPIController := example.NewResourceAPIController(ResourceAPIService)

	router := example.NewRouter(ResourceAPIController)

	log.Fatal(http.ListenAndServe(":8080", router))
}
