/*
 * Service
 *
 * API service
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package example

import (
	"context"
	"net/http"
)



// ResourceAPIRouter defines the required methods for binding the api requests to a responses for the ResourceAPI
// The ResourceAPIRouter implementation should parse necessary information from the http request,
// pass the data to a ResourceAPIServicer to perform the required actions, then write the service results to the http response.
type ResourceAPIRouter interface { 
	Create(http.ResponseWriter, *http.Request)
	Delete(http.ResponseWriter, *http.Request)
}


// ResourceAPIServicer defines the api actions for the ResourceAPI service
// This interface intended to stay up to date with the openapi yaml used to generate it,
// while the service implementation can be ignored with the .openapi-generator-ignore file
// and updated with the logic required for the API.
type ResourceAPIServicer interface { 
	Create(context.Context) (ImplResponse, error)
	Delete(context.Context, string) (ImplResponse, error)
}
